name: secrets

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS Credentials
    #  uses: aws-actions/configure-aws-credentials@v1
      env:
        aws-access-key-id: test
        aws-secret-access-key: test
        aws-region: ${{ secrets.AWS_REGION }}
    #- name: List S3 Buckets
    #  run: aws s3api list-buckets
      run: echo "region is ${{ env.aws-region }}"
